version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wb_tariffs
      - WB_API_KEY=${WB_API_KEY}
    depends_on:
      - postgres
      
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wb_tariffs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 